baseurl: "https://dataoceanlab.github.io/spatial-epi-2022"
title: "International Workshop on Spatial Computing for Epidemiology@ACM SIGSPATIAL 2022"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "SpatialEpi@ACM SIGSPATIAL 2022"
  Description: "International Workshop on Spatial Computing for Epidemiology@ACM SIGSPATIAL 2022"
  Date: "November 1, 2022, Pacific Time"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "TBA"
  Address: "TBA"
  City:  "Seattle"
  State: "Washington"
  Images: ["/img/logo.jpg"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer    
    - speakers
    - schedule    
    - location
    - cfp
    - deadline
    #- contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    speakers: "Speakers"
    schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    # contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now"
    link: ""

  intro:
    text: "The 3rd ACM SIGSPATIAL International Workshop on Spatial Computing for Epidemiology (SpatialEpi’22) focuses on all aspects of modeling, simulating, mining, and understanding the spatial processes and patterns of the spread of COVID-19 and other infectious diseases. This cross-disciplinary workshop is a forum to bring together researchers in the SIGSPATIAL community as well as researchers in epidemiology. Also, this workshop is of interest to everyone who works with infectious disease data and models (not necessarily COVID19). In addition to paper presentations, this workshop will feature invited speakers keynotes from experts across the SIGSPATIAL community and epidemiology."

  cfp:
    text: "The workshop seeks high-quality full (8-10 pages) and short (4 pages) papers that have not been published in other academic outlets and are not concurrently under peer review. Once accepted, at least one author is required to register for the workshop and the ACM SIGSPATIAL conference, as well as attend the workshop to present the accepted work which will then appear in the ACM Digital Library."
    url: "https://dataoceanlab.github.io/spatial-epi-2022/files/CFP21.pdf"
    keywords: ["Contact Tracing", 
    "COVID-19 Tracking and Data Collection", 
    "COVID-19 Data Cleaning and Wrangling", 
    "Disease Spread Simulation", "COVID-19 Data Mining", 
    "Managing Uncertainty in COVID-19 Data", 
    "COVID-19 Data Query Processing", "Mapping and Visual Analytics of COVID-19", 
    "COVID-19 Effects on Human Mobility", 
    "Prescriptive Analytics for COVID-19", 
    "COVID-19 Hotspot Detection", 
    "Socioeconomic Impact of COVID-19", 
    "COVID-19 Simulation and Modeling", 
    "Spatial Analysis of COVID-19", 
    "COVID-19 and Social Media", 
    "Spatially Explicit COVID-19 Prediction Models"]

  organizer:
    general_chair: ["Andreas Züfle (George Mason University)"]
    pc_chair: ["Taylor Anderson (George Mason University)", 
    "Joon-Seok Kim (Pacific Northwest National Laboratory)", 
    "Amira Roess (George Mason University)"]
    pc_member: ["To be announced"]

  deadline:
    submission: "September 06, 2022 (anywhere on earth) (extended)"
    notification: "September 28, 2022 (anywhere on earth)"
    camera ready: "To be announced"
    workshopdate: "November 01, 2022 (anywhere on earth)"
    submissionsite: "https://easychair.org/my/conference?conf=spatialepi21"

  speakers:
    # - name: "Amira Roess"
    #   photo: "https://chhs.gmu.edu/sites/g/files/yyqcgq286/files/profile-headshot/200-Amira%20Roess.jpg"
    #   company: "George Mason University"
    #   talk: 
    #     title: "The practicalities of multiple disciplinary research: lessons from COVID-19"
    #     abstrct: ""
    #     bio: "Dr. Roess is a professor of Global Health and Epidemiology at George Mason University's College of Health and Human Services. Her expertise is in infectious diseases epidemiology, multi-disciplinary and multi-species field research and evaluating interventions to reduce the transmission and impact of infectious diseases. Dr. Roess leads several longitudinal studies including on the emergence and transmission of Campylobacter (with support from The Bill and Melinda Gates Foundation), MERS-CoV (with support from the US National Science Foundation), development of COVID-19 in the first year of life (with support from NIH), and the development of the microbiome during the first year of life. She is also working on a number of other COVID-19 projects, including examining infection disparities and use of mHealth (especially apps) to enhance surveillance and contact tracing. Dr. Roess holds a PhD in global disease epidemiology and control from Johns Hopkins University. Her current studies are in the US, Bangladesh, Egypt, and Ethiopia. Prior to joining academia, Dr. Roess served as the Science Director for the Pew Commission on Industrial Food Animal Production at Johns Hopkins, and was an Epidemic Intelligence Service (EIS) officer at the CDC. She has served as consultant for the United States Agency for International Development, the World Bank, and Westat Inc. She has a master degree from the UMDNJ/ Rutgers University School of Public Health."
    #     href: "#schedule"
  schedule:
    # - title: "Openning remarks"
    #   time: "11-02 09:00"
    #   beijing: "11-02 21:00"
    #   abstract: ""
    #   file: "frontmatter.pdf"
    #   authors: ""
    # - title: "Keynote"
    #   time: "11-02 09:05"
    #   beijing: "11-02 21:05"      
    #   abstract: "Our workshop’s objective is to provide professionals, researchers, and practitioners interested in deriving human movement patterns from location data. We use a sample of our Weekly and Monthly Patterns and Core Places products to perform market research on a potential new coffee shop location. How far are customers willing to travel for coffee? What location will receive the most visibility? Where do most of the coffee customers come from? We’ll address these concerns and more in building a market analysis proposal in real time."
    #   file:
    # - title: "Correlation Analysis of Spatio-temporal Arabic COVID-19 Tweets"
    #   time: "11-02 10:05"
    #   beijing: "11-02 22:05"      
    #   abstract: "Our workshop’s objective is to provide professionals, researchers, and practitioners interested in deriving human movement patterns from location data. We use a sample of our Weekly and Monthly Patterns and Core Places products to perform market research on a potential new coffee shop location. How far are customers willing to travel for coffee? What location will receive the most visibility? Where do most of the coffee customers come from? We’ll address these concerns and more in building a market analysis proposal in real time."
    #   file: "paper_6.pdf"
    # - title: "Mobility Response to COVID-19-related Restrictions in New York City"
    #   time: "11-02 10:20"
    #   beijing: "11-02 22:20"      
    #   abstract: "Our workshop’s objective is to provide professionals, researchers, and practitioners interested in deriving human movement patterns from location data. We use a sample of our Weekly and Monthly Patterns and Core Places products to perform market research on a potential new coffee shop location. How far are customers willing to travel for coffee? What location will receive the most visibility? Where do most of the coffee customers come from? We’ll address these concerns and more in building a market analysis proposal in real time."
    #   file: "paper_5.pdf"
    # - title: "Developing a clustering environment for real time tracking and analysis of Covid-19 case clusters"
    #   time: "11-02 10:35"
    #   beijing: "11-02 22:35"      
    #   abstract: "Our workshop’s objective is to provide professionals, researchers, and practitioners interested in deriving human movement patterns from location data. We use a sample of our Weekly and Monthly Patterns and Core Places products to perform market research on a potential new coffee shop location. How far are customers willing to travel for coffee? What location will receive the most visibility? Where do most of the coffee customers come from? We’ll address these concerns and more in building a market analysis proposal in real time."
    #   file: "paper_1.pdf"
    # - title: "Closing Remarks"
    #   time: "11-02 10:55"
    #   beijing: "11-02 22:55"      
    #   abstract: "Our workshop’s objective is to provide professionals, researchers, and practitioners interested in deriving human movement patterns from location data. We use a sample of our Weekly and Monthly Patterns and Core Places products to perform market research on a potential new coffee shop location. How far are customers willing to travel for coffee? What location will receive the most visibility? Where do most of the coffee customers come from? We’ll address these concerns and more in building a market analysis proposal in real time."
    #   file:
